### ISSUE TITLE
Could the example of semantic SLAM be released?

### ISSUE THREAD

**Issue by qiaozhijian** [MarineRoboticsGroup/dcsam-examples#1]

**Comment by keevindoherty** [comment]
Hi! Thanks for your interest. I am hoping to do that, though I'm not sure yet when I'll be able to as I've just wrapped up my PhD and it's been hard to find time to work on these things lately!

What might help you get started in the meantime is to take a look at the DC-SAM test cases that simulate the semantic measurement models we use: https://github.com/MarineRoboticsGroup/dcsam/blob/main/tests/testDCSAM.cpp#L1184. In it, we use a simple measurement model (bearing-range + semantics), which is what we used in our paper, but this should be relatively easy to adapt to other types of measurements.

**Comment by qiaozhijian** [comment]
Thank you and congratulations on your PhD!
